/** Runtime env for Next.js API routes and Cloudflare Pages Functions. */
export type ServerEnv = {
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  CLERK_SECRET_KEY?: string;
  CLERK_WEBHOOK_SECRET?: string;
  DATABASE_URL?: string;
  NEXT_PUBLIC_APP_URL?: string;
  STRIPE_PRICE_HLV_REPORT?: string;
  STRIPE_PRICE_LEGACY_VAULT?: string;
  STRIPE_PRICE_PREMIUM_MONTHLY?: string;
  STRIPE_PRICE_PREMIUM_ANNUAL?: string;
  STRIPE_PRICE_FAMILY_FORTRESS?: string;
  STRIPE_PRICE_PREMIUM_HYBRID?: string;
  STRIPE_PRICE_ADVISOR_ANNUAL?: string;
  STRIPE_PASS_FEES_TO_CUSTOMER?: string;
  STRIPE_FEE_PERCENT?: string;
  STRIPE_FEE_FIXED_CENTS?: string;
};

export function envFromProcess(): ServerEnv {
  return {
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    CLERK_WEBHOOK_SECRET: process.env.CLERK_WEBHOOK_SECRET,
    DATABASE_URL: process.env.DATABASE_URL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    STRIPE_PRICE_HLV_REPORT: process.env.STRIPE_PRICE_HLV_REPORT,
    STRIPE_PRICE_LEGACY_VAULT: process.env.STRIPE_PRICE_LEGACY_VAULT,
    STRIPE_PRICE_PREMIUM_MONTHLY: process.env.STRIPE_PRICE_PREMIUM_MONTHLY,
    STRIPE_PRICE_PREMIUM_ANNUAL: process.env.STRIPE_PRICE_PREMIUM_ANNUAL,
    STRIPE_PRICE_FAMILY_FORTRESS: process.env.STRIPE_PRICE_FAMILY_FORTRESS,
    STRIPE_PRICE_PREMIUM_HYBRID: process.env.STRIPE_PRICE_PREMIUM_HYBRID,
    STRIPE_PRICE_ADVISOR_ANNUAL: process.env.STRIPE_PRICE_ADVISOR_ANNUAL,
    STRIPE_PASS_FEES_TO_CUSTOMER: process.env.STRIPE_PASS_FEES_TO_CUSTOMER,
    STRIPE_FEE_PERCENT: process.env.STRIPE_FEE_PERCENT,
    STRIPE_FEE_FIXED_CENTS: process.env.STRIPE_FEE_FIXED_CENTS,
  };
}

export function isStripeConfigured(env: ServerEnv): boolean {
  return Boolean(
    env.STRIPE_SECRET_KEY &&
      env.STRIPE_PRICE_HLV_REPORT &&
      env.STRIPE_PRICE_LEGACY_VAULT &&
      env.STRIPE_PRICE_PREMIUM_MONTHLY &&
      env.STRIPE_PRICE_PREMIUM_ANNUAL &&
      env.STRIPE_PRICE_FAMILY_FORTRESS &&
      env.STRIPE_PRICE_PREMIUM_HYBRID &&
      env.STRIPE_PRICE_ADVISOR_ANNUAL
  );
}
